import { createElement } from 'lwc';
import HardWordAToZButtonsList from 'c/hardWordAToZButtonsList';

describe('c-hard-word-a-to-z-buttons-list', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-hard-word-a-to-z-buttons-list', {
            is: HardWordAToZButtonsList
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});